### PR TITLE
Feature_issue2 :duplicate the hello world

### PR DESCRIPTION
**Pull request by Vechyeny**
duplicate the hello world #2

### CODE REVIEW

**Comment by selaxyz** [comment]
please rebase the develop branch into the feature branch you are currently working on different commit head.

**Comment by Vechyeny** [comment]
Hello, I have received the msg and I wonder how rebase working, can You can help dude!!

**Comment by selaxyz** [comment]
there is a git command called 'rebase'

**Review by selaxyz — APPROVED** [review]
.

**Pull request closed without merging**
